### PR TITLE
avoid overwriting of scripts (software-4233)

### PR DESCRIPTION
**Pull request by ddavila0**

### CODE REVIEW

**Comment by djw8605** [comment]
@matyasselmeci could you take a look?

**Review by matyasselmeci — APPROVED** [review]
LGTM.

**Comment by djw8605** [comment]
It looks like I don't need to put out a new release since this is just a packaging fix?

**Comment by matyasselmeci** [comment]
OSG has its own copy of the spec file so yes, making a tag isn't necessary.

**Pull request merged**
