### PR TITLE
Adding EC to the admin-create-key

### LINKED ISSUE #78: Augment the scitokens-admin-create-key script for EC
There's no obvious way to generate an EC key for use in the server.  `scitokens-admin-create-key` only generates RSA keys.

There should be a new flag that allows us to easily make EC keys.

### PR DESCRIPTION
**Pull request by djw8605**
Fixes #78 

I tested this with just simple commands.

### CODE REVIEW

**Comment by bbockelm** [comment]
Can you also adopt the test case for EC: https://github.com/scitokens/scitokens/blob/master/tests/test_admin_create_key.py ?

**Comment by djw8605** [comment]
I swear I looked for the tests and couldn't find them.  Oh well, modified.

**Comment by bbockelm** [comment]
Looks like some simple whitespace issues from Codacy, not too much to fix.

**Comment by djw8605** [comment]
Odd, codacy email went to my spam.

**Pull request merged**
